### PR TITLE
Update to nvidia installer for new Optimus support in NVIDIA drivers.

### PR DESCRIPTION
**Pull request by rwoliver2**
This will properly install nvidia drivers (and not bumblebee) for modern xorg and NVIDIA Optimus systems.

### CODE REVIEW

**Comment by dolphinoracle** [comment]
we are exploring the method of operation of optimus with the  nvidia-driver here:  https://forum.mxlinux.org/viewtopic.php?f=138&t=62642

so far no one has got it to work.

**Comment by rwoliver2** [comment]
Any updates so far? I've tested it on two systems without issues but I know we need more confirmations.

**Comment by dolphinoracle** [comment]
I have a optimus laptop on the way to test.   our only tester in the forum did not get the system to work.

the patch itself is only partially ok, even if the methodology works.  It will be fine for bullseye, but on debian we would need to check the xorg version or something first.  using nvidia-driver without bumblebee will not work on the debian-stable version of xorg on both mx standard releases and antiX standard releases.

**Comment by rwoliver2** [comment]
I can modify this to be more robust. Should I check for MX version, as I do now, or xorg version?

**Comment by rwoliver2** [comment]
Added detection of xorg version.

**Comment by dolphinoracle** [comment]
I just realized you have submitted patch against the master branch.  we quit using that, in lieu of the "buster" branch.  idea is the same but there are more checks dealing with legacy drivers and bumblebee/optimus in the buster series.

**Comment by dolphinoracle** [comment]
closing this one.

**Pull request closed without merging**
